#They're all bangers frfr
SONGS: list[str] = ["Chocolat Cadabra - Ado",
                    "Villain - Ado",
                    "Usseewa - Ado",
                    "All Night Radio - Ado",
                    "SPECIALZ - King Gnu",
                    "Yoyoi Kokon - REOL",
                    "Kazarijyanainoyonamidawa - Ado",
                    "Aishite Aishite Aishite - Ado",
                    "Ibara - Ado",
                    "impulse - AliA",
                    "Till the End - ReoNa",
                    "Cattleya - Shiyui",
                    "Kura Kura - Ado",
                    "Akatsuki Zakura - GARNiDELiA",
                    "ChiruChiru - REOL",
                    "LEADER - MY FIRST STORY",
                    "REVIVER - MY FIRST STORY",
                    "KICK BACK - Kenshi Yonezu",
                    "Drink, Pray, Love! - Yuinishio",
                    "Gokusaishiki - REOL",
                    "REALiZE - LiSA",
                    "Crime and Punishment - Ado",
                    "怪物 - YOASOBI",
                    ]