name: run main.py

on:
  push: { branches: [main, develop] }

# Testing dependencies
jobs:
  # Testing for Python 3.8
  python38:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Testing for Python 3.9
  python39:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        


  # Testing for Python 3.10
  python310:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        

  # Testing for Python 3.11
  python311:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        

  # Testing for Python 3.12
  python312:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt